# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 834436766ff8999035be52d3cef041a3b91060cf0e4e92e03023f54db834478d126d415cf4cc75b7ddfd0ebcb784b6a5b3cc732ae95aea23c420e388bfb2d5fc

test:
  secret_key_base: 2d877a5e9486e3352f54d9c8866d2b9af82ef9d33a84f8e6290851d3c694c33eb3f69f6842b53e871349ce11cf082e67cd28aa741889cc2b0a036586168c1208

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
